spring:
  application:
    name: pp
  datasource:
    url: jdbc:postgresql://localhost:5432/pp
    username: postgres
    password: sopra*
    driverClassName: org.postgresql.Driver
  thymeleaf:
    prefix: /WEB-INF/views/
    cache: false
server:
  contextPath: /pp
management:
  contextPath: /admin
debug: false