spring:
  application:
    name: pp
  datasource:
    url: jdbc:postgresql://localhost:5432/pp
    username: postgres
    password: sopra*
    driverClassName: org.postgresql.Driver
  jpa:
    openInView: false
    hibernate:
      ddl-auto: validate
  thymeleaf:
    prefix: /WEB-INF/views/
    cache: false
management:
  contextPath: /admin
liquibase:
  change-log: classpath:/db/changelog.xml
debug: false